### ISSUE TITLE
[ISSUE] Test Case fails when User is Eager fetched

### ISSUE THREAD

**Issue by rajat-g** [yannbriancon/spring-hibernate-query-count#10]
The test cases fail in the new package as when User is fetched Eagerly as opposed to Lazy then the message is empty and because of that, the test case fails. 

The root cause is when lazy fetched -
stackTraceElement.getClassName().indexOf(entityName) == 0 is true
but when eager fetched it is false.

The old package detects this eager N+1 queries as it didn't had this function

**Comment by yannbriancon** [comment]
The version 1.0.3 has been released with a new way of detecting the eager fetching that should avoid false positive.

Enjoy!

**Comment by rajat-g** [comment]
I checked it out and it is working again. Thanks for the quick fix. 

However, I found some code issue which will. not make a difference as such -
1. In method `getProxyMethodName` you could have used PROXY_METHOD_PREFIX instead of hardcoding it.
2. No use to return type in methods `detectNPlusOneQueriesOfMissingQueryEagerFetching` and `detectNPlusOneQueriesOfMissingEntityFieldLazyFetching`

**Comment by yannbriancon** [comment]
Perfect!

Thanks for the feedback on the code I forgot to use this variable
