### ISSUE TITLE
Release 2.0 is not in maven central 

### ISSUE THREAD

**Issue by strogiyotec** [yannbriancon/spring-hibernate-query-count#19]
Hey, thanks for this awesome project, as far as I can see the latest version is 2.0 but it's not in maven central. I need new version in order to be able to disable query-utils for specific profiles (enable property is not present in latest release 1.3). Could you upload a new version please . Cheers

**Comment by yannbriancon** [comment]
Hey!

Sorry it was a mistake on my side, it is now released ;)

Thanks for your return

**Comment by strogiyotec** [comment]
Thanks a lot , Regards !
